### ISSUE TITLE
It is checked if a contract is a member of the consortium

### ISSUE THREAD

**Issue by eduadiez** [ipfsconsortium/IPFSConsortiumProxy#2]
It doesn't make sense to check that a contract belongs to the consortium since in any cases it'll be a member:
https://github.com/ipfsconsortium/IPFSConsortiumProxy/blob/bdd29aef743f41b353bbe011c0ab5d082e4e154d/src/ipfsconsortiumproxy.js#L190

**Comment by eduadiez** [comment]
I think we need to add to:

https://github.com/ipfsconsortium/IPFSConsortiumContracts/blob/2a54c165d5678bf8d5bd7af7bd05f7447d71ffe2/contracts/IPFSProxy.sol#L23

the member who added the contract to be able to track the quota:

```
event ContractAdded(address member, address pubKey, uint ttl);
```

**Comment by sponnet** [comment]
The msg.sender that generates the event will be a member because of
the onlyValidMembers
modifier

But you are right that the accounting code probably isn't taking that into
account.

You're also right that that would be an improvement in the consortium
contract code.

**Comment by sponnet** [comment]
fixed in current version
